/* 肉桂狗卡池：100 張獨立卡片，圖片不重複；稀有度愈高圖愈華麗 */
const CINNA_IMG = {
  party: 'assets/img/cinnamoroll/cinnamoroll-party.png',
  prince: 'assets/img/cinnamoroll/cinnamoroll-prince.png',
  winter: 'assets/img/cinnamoroll/cinnamoroll-winter.png',
  solo: 'assets/img/cinnamoroll/cinnamoroll-solo.png',
  mocha: 'assets/img/cinnamoroll/cinna-mocha.png',
  milk: 'assets/img/cinnamoroll/cinna-milk.png',
  chiffon: 'assets/img/cinnamoroll/cinna-chiffon.png',
  cappuccino: 'assets/img/cinnamoroll/cinna-cappuccino.png',
  espresso: 'assets/img/cinnamoroll/cinna-espresso.png',
  ref: (n) => `assets/img/cinnamoroll/cards/ref-${String(n).padStart(3, '0')}.png`,
  art: (n) => `assets/img/cinnamoroll/cards/art-${String(n).padStart(3, '0')}.svg`
};

const CINNAMOROLL_DECK = [
  /* ── 傳說 SSR ×3（最華麗場景卡）── */
  { name: '肉桂狗和朋友·永遠版', rarity: 'ssr', img: CINNA_IMG.party, desc: '生日派對全員到齊，蛋糕、氣球同禮物滿載！' },
  { name: '肉桂狗·皇家音樂會', rarity: 'ssr', img: CINNA_IMG.prince, desc: '皇冠、禮服同豎琴，皇家音樂巡遊最華麗一刻。' },
  { name: '肉桂狗·星空星座', rarity: 'ssr', img: CINNA_IMG.ref(5), desc: '深夜星空、星座天馬，同你一齊遨遊宇宙。' },

  /* ── 極稀有 UR ×10 ── */
  { name: '肉桂狗和朋友·壽司聯名', rarity: 'ur', img: CINNA_IMG.ref(16), desc: 'Sushiro 聯名冬日夜景，壽司星座閃閃發光。' },
  { name: '肉桂狗和朋友·極光團聚', rarity: 'ur', img: CINNA_IMG.ref(17), desc: '雪地圍巾、星光滿天，朋友仔暖暖團聚。' },
  { name: '肉桂狗和朋友·冬日版', rarity: 'ur', img: CINNA_IMG.winter, desc: '雪花紛飛冬日慶典，肉桂狗同伙伴齊聚。' },
  { name: '肉桂狗·夏日派對', rarity: 'ur', img: CINNA_IMG.ref(14), desc: '沙灘汽水、太陽眼鏡，夏日狂歡派對！' },
  { name: '肉桂狗·慶典煙花', rarity: 'ur', img: CINNA_IMG.ref(15), desc: '彩帶煙花、甜蜜慶祝，華麗節日氣氛。' },
  { name: '肉桂狗·夏日徽章', rarity: 'ur', img: CINNA_IMG.ref(3), desc: 'Sanrio 夏日徽章系列，六角色齊晒。' },
  { name: '肉桂狗·雲海飛行', rarity: 'ur', img: CINNA_IMG.ref(6), desc: '乘著長耳朵飛過雲海，藍天白雲好夢幻。' },
  { name: '肉桂狗·茶會盛宴', rarity: 'ur', img: CINNA_IMG.ref(7), desc: '茶杯禮帽、精緻茶點，夢幻下午茶。' },
  { name: '肉桂狗·星願籃子', rarity: 'ur', img: CINNA_IMG.ref(9), desc: 'Sanrio 朋友仔齊坐花籃，繽紛夏日風。' },
  { name: '肉桂狗·銀河漫步', rarity: 'ur', img: CINNA_IMG.ref(24), desc: '銀河星球、閃亮星塵，漫步奇幻夜空。' },

  /* ── 超稀有 SR ×12 ── */
  { name: '濃縮咖啡·紳士版', rarity: 'sr', img: CINNA_IMG.espresso, desc: '優雅紳士造型，濃縮咖啡好帥氣！' },
  { name: '牛奶·彩虹毯版', rarity: 'sr', img: CINNA_IMG.milk, desc: '奶嘴同彩虹小毯，奶味十足超可愛。' },
  { name: '芙蘭·雪花版', rarity: 'sr', img: CINNA_IMG.chiffon, desc: '毛茸茸芙蘭，雪花圍巾暖呼呼。' },
  { name: '摩卡·櫻花版', rarity: 'sr', img: CINNA_IMG.mocha, desc: '蝴蝶結摩卡，櫻花飄落好浪漫。' },
  { name: '卡布奇諾·耳罩版', rarity: 'sr', img: CINNA_IMG.cappuccino, desc: '暖暖耳罩卡布奇諾，冬日慵懒風。' },
  { name: '肉桂狗·雲朵飄飄', rarity: 'sr', img: CINNA_IMG.ref(2), desc: '多隻肉桂狗浮在雲端，夢幻天空圖案。' },
  { name: '肉桂狗·泰迪熊驚喜', rarity: 'sr', img: CINNA_IMG.ref(10), desc: '抱著小熊從畫面探頭，驚喜滿滿。' },
  { name: '肉桂狗·雪糕甜蜜', rarity: 'sr', img: CINNA_IMG.ref(11), desc: '手拿雪糕、雪花飄飄，甜蜜冬日滋味。' },
  { name: '肉桂狗·星座許願', rarity: 'sr', img: CINNA_IMG.ref(23), desc: '仰望星空許願，星座閃爍好神奇。' },
  { name: '肉桂狗·經典版', rarity: 'sr', img: CINNA_IMG.solo, desc: '經典肉桂狗造型，長耳朵藍眼睛。' },
  { name: '肉桂狗·雲朵午睡', rarity: 'sr', img: CINNA_IMG.ref(8), desc: '躺在雲朵上午睡，舒服到打哈欠。' },
  { name: '肉桂狗·花園野餐', rarity: 'sr', img: CINNA_IMG.ref(12), desc: '花園野餐墊上，享受陽光同點心。' },

  /* ── 稀有 Rare ×25 ── */
  { name: '肉桂狗·泰迪探頭', rarity: 'rare', img: CINNA_IMG.ref(1), desc: '抱著小熊好奇探頭，萌度爆表。' },
  { name: '肉桂狗·雪糕座', rarity: 'rare', img: CINNA_IMG.ref(4), desc: '坐在雪地裡吃雪糕，開心笑呵呵。' },
  { name: '肉桂狗·花園散步', rarity: 'rare', img: CINNA_IMG.ref(13), desc: '花園小徑散步，微風吹過長耳朵。' },
  { name: '肉桂狗·萌萌臉', rarity: 'rare', img: CINNA_IMG.ref(18), desc: '特寫萌萌臉蛋，藍眼睛粉腮紅。' },
  { name: '肉桂狗·眨眼版', rarity: 'rare', img: CINNA_IMG.ref(19), desc: '俏皮眨眼，逗你開心。' },
  { name: '肉桂狗·微笑版', rarity: 'rare', img: CINNA_IMG.ref(20), desc: '甜甜微笑，治癒系小天使。' },
  { name: '肉桂狗·簡約版', rarity: 'rare', img: CINNA_IMG.ref(21), desc: '簡約線條風，清新可愛。' },
  { name: '肉桂狗·迷你版', rarity: 'rare', img: CINNA_IMG.ref(22), desc: '迷你Q版造型，放進口袋剛好。' },
  { name: '摩卡·蝴蝶結版', rarity: 'rare', img: CINNA_IMG.art(58), desc: '粉蝴蝶結摩卡，甜美登場。' },
  { name: '牛奶·奶嘴版', rarity: 'rare', img: CINNA_IMG.art(59), desc: '含著奶嘴的牛奶，軟綿綿。' },
  { name: '芙蘭·毛帽版', rarity: 'rare', img: CINNA_IMG.art(60), desc: '戴毛帽的芙蘭，暖笠笠。' },
  { name: '卡布奇諾·枕頭版', rarity: 'rare', img: CINNA_IMG.art(61), desc: '抱枕頭打瞌睡的卡布奇諾。' },
  { name: '濃縮咖啡·背包版', rarity: 'rare', img: CINNA_IMG.art(62), desc: '背著小背包準備探險。' },
  { name: '肉桂狗·雲朵版', rarity: 'rare', img: CINNA_IMG.art(63), desc: '坐在軟綿綿雲朵上發呆。' },
  { name: '肉桂狗·星星版', rarity: 'rare', img: CINNA_IMG.art(64), desc: '手捧閃亮小星星。' },
  { name: '肉桂狗·圍巾版', rarity: 'rare', img: CINNA_IMG.art(65), desc: '粉白條紋圍巾，冬日必備。' },
  { name: '肉桂狗·草莓版', rarity: 'rare', img: CINNA_IMG.art(66), desc: '頭頂草莓，甜甜水果風。' },
  { name: '肉桂狗·牛奶糖版', rarity: 'rare', img: CINNA_IMG.art(67), desc: '牛奶糖色調，軟糯可愛。' },
  { name: '肉桂狗·棉花糖版', rarity: 'rare', img: CINNA_IMG.art(68), desc: '像棉花糖一樣輕盈蓬鬆。' },
  { name: '肉桂狗·晴天版', rarity: 'rare', img: CINNA_IMG.art(69), desc: '晴天太陽下蹦蹦跳跳。' },
  { name: '肉桂狗·雨天版', rarity: 'rare', img: CINNA_IMG.art(70), desc: '撐小雨傘，雨滴叮叮噹。' },
  { name: '肉桂狗·咖啡廳版', rarity: 'rare', img: CINNA_IMG.art(71), desc: '咖啡廳角落靜靜享受下午茶。' },
  { name: '肉桂狗·睡覺版', rarity: 'rare', img: CINNA_IMG.art(72), desc: '抱著枕頭呼呼大睡。' },
  { name: '肉桂狗·飛行版', rarity: 'rare', img: CINNA_IMG.art(73), desc: '耳朵當翅膀，咻一聲飛走。' },
  { name: '肉桂狗·生日版', rarity: 'rare', img: CINNA_IMG.art(74), desc: '戴生日帽吹蠟燭，好開心。' },

  /* ── 普通 Common ×50 ── */
  { name: '肉桂狗·雲朵 No.1', rarity: 'common', img: CINNA_IMG.art(33), desc: '普通雲朵系列卡片。' },
  { name: '肉桂狗·星星 No.2', rarity: 'common', img: CINNA_IMG.art(34), desc: '普通星星系列卡片。' },
  { name: '摩卡·下午茶 No.3', rarity: 'common', img: CINNA_IMG.art(35), desc: '摩卡下午茶時光。' },
  { name: '牛奶·搖籃 No.4', rarity: 'common', img: CINNA_IMG.art(36), desc: '牛奶在搖籃裡打盹。' },
  { name: '芙蘭·滑雪 No.5', rarity: 'common', img: CINNA_IMG.art(37), desc: '芙蘭第一次滑雪。' },
  { name: '卡布奇諾·午覺 No.6', rarity: 'common', img: CINNA_IMG.art(38), desc: '卡布奇諾午覺時間。' },
  { name: '濃縮咖啡·地圖 No.7', rarity: 'common', img: CINNA_IMG.art(39), desc: '濃縮咖啡研究地圖。' },
  { name: '肉桂狗·櫻花 No.8', rarity: 'common', img: CINNA_IMG.art(40), desc: '櫻花樹下野餐。' },
  { name: '肉桂狗·蝴蝶結 No.9', rarity: 'common', img: CINNA_IMG.art(41), desc: '頸上蝴蝶結好靚。' },
  { name: '肉桂狗·草莓 No.10', rarity: 'common', img: CINNA_IMG.art(42), desc: '草莓甜點時間。' },
  { name: '肉桂狗·牛奶糖 No.11', rarity: 'common', img: CINNA_IMG.art(43), desc: '牛奶糖香味撲鼻。' },
  { name: '肉桂狗·棉花糖 No.12', rarity: 'common', img: CINNA_IMG.art(44), desc: '棉花糖雲朵般柔軟。' },
  { name: '肉桂狗·晴天 No.13', rarity: 'common', img: CINNA_IMG.art(45), desc: '晴天出門散步。' },
  { name: '肉桂狗·雨天 No.14', rarity: 'common', img: CINNA_IMG.art(46), desc: '雨天在家看窗外。' },
  { name: '肉桂狗·聖誕 No.15', rarity: 'common', img: CINNA_IMG.art(47), desc: '聖誕帽同小禮物。' },
  { name: '肉桂狗·新年 No.16', rarity: 'common', img: CINNA_IMG.art(48), desc: '新年利是好運到。' },
  { name: '摩卡·購物 No.17', rarity: 'common', img: CINNA_IMG.art(49), desc: '摩卡逛街買甜品。' },
  { name: '牛奶·玩具熊 No.18', rarity: 'common', img: CINNA_IMG.art(50), desc: '牛奶抱玩具熊入睡。' },
  { name: '芙蘭·雪人 No.19', rarity: 'common', img: CINNA_IMG.art(51), desc: '芙蘭堆了一個小雪人。' },
  { name: '卡布奇諾·毛毯 No.20', rarity: 'common', img: CINNA_IMG.art(52), desc: '卡布奇諾裹毛毯睇書。' },
  { name: '濃縮咖啡·禮帽 No.21', rarity: 'common', img: CINNA_IMG.art(53), desc: '濃縮咖啡戴禮帽。' },
  { name: '肉桂狗·音符 No.22', rarity: 'common', img: CINNA_IMG.art(54), desc: '哼着小曲好開心。' },
  { name: '肉桂狗·氣球 No.23', rarity: 'common', img: CINNA_IMG.art(55), desc: '手拿彩色氣球。' },
  { name: '肉桂狗·禮物 No.24', rarity: 'common', img: CINNA_IMG.art(56), desc: '神秘禮物盒一份。' },
  { name: '肉桂狗·雪花 No.25', rarity: 'common', img: CINNA_IMG.art(57), desc: '接住一片小雪花。' },
  { name: '肉桂狗·彩虹 No.26', rarity: 'common', img: CINNA_IMG.art(75), desc: '雨後彩虹好靚。' },
  { name: '肉桂狗·月亮 No.27', rarity: 'common', img: CINNA_IMG.art(76), desc: '月光下輕輕飛翔。' },
  { name: '摩卡·拍照 No.28', rarity: 'common', img: CINNA_IMG.art(77), desc: '摩卡舉相機自拍。' },
  { name: '牛奶·泡泡 No.29', rarity: 'common', img: CINNA_IMG.art(78), desc: '牛奶吹彩色泡泡。' },
  { name: '芙蘭·熱可可 No.30', rarity: 'common', img: CINNA_IMG.art(79), desc: '芙蘭捧熱可可暖手。' },
  { name: '卡布奇諾·慵懶 No.31', rarity: 'common', img: CINNA_IMG.art(80), desc: '慵懶伸懶腰。' },
  { name: '濃縮咖啡·筆記 No.32', rarity: 'common', img: CINNA_IMG.art(81), desc: '濃縮咖啡寫筆記。' },
  { name: '肉桂狗·花朵 No.33', rarity: 'common', img: CINNA_IMG.art(82), desc: '頭戴小花冠。' },
  { name: '肉桂狗·愛心 No.34', rarity: 'common', img: CINNA_IMG.art(83), desc: '比心心送俾你。' },
  { name: '肉桂狗·糖果 No.35', rarity: 'common', img: CINNA_IMG.art(84), desc: '糖果罐裝滿甜蜜。' },
  { name: '肉桂狗·餅乾 No.36', rarity: 'common', img: CINNA_IMG.art(85), desc: '剛出爐小餅乾。' },
  { name: '肉桂狗·蛋糕 No.37', rarity: 'common', img: CINNA_IMG.art(86), desc: '小蛋糕好诱人。' },
  { name: '肉桂狗·冰淇淋 No.38', rarity: 'common', img: CINNA_IMG.art(87), desc: '三球冰淇淋！' },
  { name: '肉桂狗·太陽 No.39', rarity: 'common', img: CINNA_IMG.art(88), desc: '向太陽說早安。' },
  { name: '肉桂狗·咖啡 No.40', rarity: 'common', img: CINNA_IMG.art(89), desc: '早晨一杯咖啡。' },
  { name: '摩卡·甜品 No.41', rarity: 'common', img: CINNA_IMG.art(90), desc: '摩卡甜品時光。' },
  { name: '牛奶·糖果 No.42', rarity: 'common', img: CINNA_IMG.art(91), desc: '牛奶含糖果笑咪咪。' },
  { name: '芙蘭·手套 No.43', rarity: 'common', img: CINNA_IMG.art(92), desc: '芙蘭戴暖暖手套。' },
  { name: '卡布奇諾·柔軟 No.44', rarity: 'common', img: CINNA_IMG.art(93), desc: '柔軟蓬鬆好舒服。' },
  { name: '濃縮咖啡·望遠鏡 No.45', rarity: 'common', img: CINNA_IMG.art(94), desc: '用望遠鏡看星星。' },
  { name: '肉桂狗·風箏 No.46', rarity: 'common', img: CINNA_IMG.art(95), desc: '放風箏好得意。' },
  { name: '肉桂狗·貝殼 No.47', rarity: 'common', img: CINNA_IMG.art(96), desc: '海邊拾貝殼。' },
  { name: '肉桂狗·楓葉 No.48', rarity: 'common', img: CINNA_IMG.art(97), desc: '秋天楓葉飄落。' },
  { name: '肉桂狗·鈴鐺 No.49', rarity: 'common', img: CINNA_IMG.art(98), desc: '頸上小鈴鐺叮噹響。' },
  { name: '肉桂狗·限定 No.50', rarity: 'common', img: CINNA_IMG.art(99), desc: '限定普通版收藏卡。' }
];
