/* SANRIO_DECK 卡池：100 張獨立卡片，每角色最多 2 張 */
const SANRIO_ART_VER = 5;
const SANRIO_IMG = {
  art: (n) => `assets/img/cinnamoroll/cards/art-${String(n).padStart(3, '0')}.svg?v=${SANRIO_ART_VER}`
};

const SANRIO_DECK = [
  { name: 'Hello Kitty·紅蝴蝶結', rarity: 'ssr', img: SANRIO_IMG.art(1), desc: '傳說 · Hello Kitty 紅蝴蝶結' },
  { name: 'Hello Kitty·藍吊帶褲', rarity: 'ssr', img: SANRIO_IMG.art(2), desc: '傳說 · Hello Kitty 藍吊帶褲' },
  { name: '美樂蒂·粉紅帽兜', rarity: 'ssr', img: SANRIO_IMG.art(3), desc: '傳說 · 美樂蒂 粉紅帽兜' },
  { name: '美樂蒂·野餐籃子', rarity: 'ur', img: SANRIO_IMG.art(4), desc: '極稀有 · 美樂蒂 野餐籃子' },
  { name: '庫洛米·惡魔帽兜', rarity: 'ur', img: SANRIO_IMG.art(5), desc: '極稀有 · 庫洛米 惡魔帽兜' },
  { name: '庫洛米·骷髏頭巾', rarity: 'ur', img: SANRIO_IMG.art(6), desc: '極稀有 · 庫洛米 骷髏頭巾' },
  { name: '肉桂狗·彩帶飛天', rarity: 'ur', img: SANRIO_IMG.art(7), desc: '極稀有 · 肉桂狗 彩帶飛天' },
  { name: '肉桂狗·雲端飛行', rarity: 'ur', img: SANRIO_IMG.art(8), desc: '極稀有 · 肉桂狗 雲端飛行' },
  { name: '布丁狗·貝雷帽', rarity: 'ur', img: SANRIO_IMG.art(9), desc: '極稀有 · 布丁狗 貝雷帽' },
  { name: '布丁狗·巨餅舞台', rarity: 'ur', img: SANRIO_IMG.art(10), desc: '極稀有 · 布丁狗 巨餅舞台' },
  { name: '大眼蛙·荷葉青蛙', rarity: 'ur', img: SANRIO_IMG.art(11), desc: '極稀有 · 大眼蛙 荷葉青蛙' },
  { name: '大眼蛙·手風琴演奏', rarity: 'ur', img: SANRIO_IMG.art(12), desc: '極稀有 · 大眼蛙 手風琴演奏' },
  { name: '蛋黃哥·懶懶煎蛋', rarity: 'ur', img: SANRIO_IMG.art(13), desc: '極稀有 · 蛋黃哥 懶懶煎蛋' },
  { name: '蛋黃哥·海灘吐司', rarity: 'sr', img: SANRIO_IMG.art(14), desc: '超稀有 · 蛋黃哥 海灘吐司' },
  { name: '酷企鵝·搖滾墨鏡', rarity: 'sr', img: SANRIO_IMG.art(15), desc: '超稀有 · 酷企鵝 搖滾墨鏡' },
  { name: '酷企鵝·滑板極限', rarity: 'sr', img: SANRIO_IMG.art(16), desc: '超稀有 · 酷企鵝 滑板極限' },
  { name: '帕恰狗·藍耳奔馳', rarity: 'sr', img: SANRIO_IMG.art(17), desc: '超稀有 · 帕恰狗 藍耳奔馳' },
  { name: '帕恰狗·足球熱血', rarity: 'sr', img: SANRIO_IMG.art(18), desc: '超稀有 · 帕恰狗 足球熱血' },
  { name: '奇奇·星星閃耀', rarity: 'sr', img: SANRIO_IMG.art(19), desc: '超稀有 · 奇奇 星星閃耀' },
  { name: '奇奇·彩虹拱門', rarity: 'sr', img: SANRIO_IMG.art(20), desc: '超稀有 · 奇奇 彩虹拱門' },
  { name: '拉拉·月亮甜夢', rarity: 'sr', img: SANRIO_IMG.art(21), desc: '超稀有 · 拉拉 月亮甜夢' },
  { name: '拉拉·太陽暖暖', rarity: 'sr', img: SANRIO_IMG.art(22), desc: '超稀有 · 拉拉 太陽暖暖' },
  { name: '燕尾服山姆·領結紳士', rarity: 'sr', img: SANRIO_IMG.art(23), desc: '超稀有 · 燕尾服山姆 領結紳士' },
  { name: '燕尾服山姆·壽司聯名', rarity: 'sr', img: SANRIO_IMG.art(24), desc: '超稀有 · 燕尾服山姆 壽司聯名' },
  { name: '漢頓·噴水海洋', rarity: 'sr', img: SANRIO_IMG.art(25), desc: '超稀有 · 漢頓 噴水海洋' },
  { name: '漢頓·海洋探險', rarity: 'rare', img: SANRIO_IMG.art(26), desc: '稀有 · 漢頓 海洋探險' },
  { name: '烈子·金屬搖滾', rarity: 'rare', img: SANRIO_IMG.art(27), desc: '稀有 · 烈子 金屬搖滾' },
  { name: '烈子·電子琴搖滾', rarity: 'rare', img: SANRIO_IMG.art(28), desc: '稀有 · 烈子 電子琴搖滾' },
  { name: '淘氣猴·淘氣香蕉', rarity: 'rare', img: SANRIO_IMG.art(29), desc: '稀有 · 淘氣猴 淘氣香蕉' },
  { name: '淘氣猴·叢林藤蔓', rarity: 'rare', img: SANRIO_IMG.art(30), desc: '稀有 · 淘氣猴 叢林藤蔓' },
  { name: '巧克貓·巧克力夜', rarity: 'rare', img: SANRIO_IMG.art(31), desc: '稀有 · 巧克貓 巧克力夜' },
  { name: '巧克貓·黑貓夜行', rarity: 'rare', img: SANRIO_IMG.art(32), desc: '稀有 · 巧克貓 黑貓夜行' },
  { name: '毛毯熊·毛毯暖暖', rarity: 'rare', img: SANRIO_IMG.art(33), desc: '稀有 · 毛毯熊 毛毯暖暖' },
  { name: '毛毯熊·枕頭午睡', rarity: 'rare', img: SANRIO_IMG.art(34), desc: '稀有 · 毛毯熊 枕頭午睡' },
  { name: '邦邦兔·緞帶公主', rarity: 'rare', img: SANRIO_IMG.art(35), desc: '稀有 · 邦邦兔 緞帶公主' },
  { name: '邦邦兔·禮物緞帶', rarity: 'rare', img: SANRIO_IMG.art(36), desc: '稀有 · 邦邦兔 禮物緞帶' },
  { name: '許願兔·許願流星', rarity: 'rare', img: SANRIO_IMG.art(37), desc: '稀有 · 許願兔 許願流星' },
  { name: '許願兔·兔子許願', rarity: 'rare', img: SANRIO_IMG.art(38), desc: '稀有 · 許願兔 兔子許願' },
  { name: '必愛諾·綿羊鋼琴', rarity: 'rare', img: SANRIO_IMG.art(39), desc: '稀有 · 必愛諾 綿羊鋼琴' },
  { name: '必愛諾·愛心抱抱', rarity: 'rare', img: SANRIO_IMG.art(40), desc: '稀有 · 必愛諾 愛心抱抱' },
  { name: '丹尼爾·紳士禮帽', rarity: 'rare', img: SANRIO_IMG.art(41), desc: '稀有 · 丹尼爾 紳士禮帽' },
  { name: '丹尼爾·玫瑰紳士', rarity: 'rare', img: SANRIO_IMG.art(42), desc: '稀有 · 丹尼爾 玫瑰紳士' },
  { name: '佩可醬·藍衣鴨鴨', rarity: 'rare', img: SANRIO_IMG.art(43), desc: '稀有 · 佩可醬 藍衣鴨鴨' },
  { name: '佩可醬·泳圈鴨鴨', rarity: 'rare', img: SANRIO_IMG.art(44), desc: '稀有 · 佩可醬 泳圈鴨鴨' },
  { name: '田寶·笑口常開', rarity: 'rare', img: SANRIO_IMG.art(45), desc: '稀有 · 田寶 笑口常開' },
  { name: '田寶·開心大笑', rarity: 'rare', img: SANRIO_IMG.art(46), desc: '稀有 · 田寶 開心大笑' },
  { name: '三文魚·三文魚片', rarity: 'rare', img: SANRIO_IMG.art(47), desc: '稀有 · 三文魚 三文魚片' },
  { name: '三文魚·壽司盤子', rarity: 'rare', img: SANRIO_IMG.art(48), desc: '稀有 · 三文魚 壽司盤子' },
  { name: '蜜糖邦妮·蜜糖花園', rarity: 'rare', img: SANRIO_IMG.art(49), desc: '稀有 · 蜜糖邦妮 蜜糖花園' },
  { name: '蜜糖邦妮·邦妮花園', rarity: 'rare', img: SANRIO_IMG.art(50), desc: '稀有 · 蜜糖邦妮 邦妮花園' },
  { name: '鋼牙妹·金屬牙套', rarity: 'common', img: SANRIO_IMG.art(51), desc: '普通 · 鋼牙妹 金屬牙套' },
  { name: '鋼牙妹·牙套閃耀', rarity: 'common', img: SANRIO_IMG.art(52), desc: '普通 · 鋼牙妹 牙套閃耀' },
  { name: '野狼健·野營嚎叫', rarity: 'common', img: SANRIO_IMG.art(53), desc: '普通 · 野狼健 野營嚎叫' },
  { name: '野狼健·月亮嚎叫', rarity: 'common', img: SANRIO_IMG.art(54), desc: '普通 · 野狼健 月亮嚎叫' },
  { name: '小浣熊·洗臉浣熊', rarity: 'common', img: SANRIO_IMG.art(55), desc: '普通 · 小浣熊 洗臉浣熊' },
  { name: '小浣熊·森林浣洗', rarity: 'common', img: SANRIO_IMG.art(56), desc: '普通 · 小浣熊 森林浣洗' },
  { name: '海獅君·頂球海獅', rarity: 'common', img: SANRIO_IMG.art(57), desc: '普通 · 海獅君 頂球海獅' },
  { name: '海獅君·球技表演', rarity: 'common', img: SANRIO_IMG.art(58), desc: '普通 · 海獅君 球技表演' },
  { name: '鴨仔雷蒙·雷蒙帽子', rarity: 'common', img: SANRIO_IMG.art(59), desc: '普通 · 鴨仔雷蒙 雷蒙帽子' },
  { name: '鴨仔雷蒙·鴨帽造型', rarity: 'common', img: SANRIO_IMG.art(60), desc: '普通 · 鴨仔雷蒙 鴨帽造型' },
  { name: '摩卡·摩卡咖啡', rarity: 'common', img: SANRIO_IMG.art(61), desc: '普通 · 摩卡 摩卡咖啡' },
  { name: '摩卡·櫻花摩卡', rarity: 'common', img: SANRIO_IMG.art(62), desc: '普通 · 摩卡 櫻花摩卡' },
  { name: '牛奶·搖籃牛奶', rarity: 'common', img: SANRIO_IMG.art(63), desc: '普通 · 牛奶 搖籃牛奶' },
  { name: '牛奶·彩虹毯子', rarity: 'common', img: SANRIO_IMG.art(64), desc: '普通 · 牛奶 彩虹毯子' },
  { name: '芙蘭·雪花芙蘭', rarity: 'common', img: SANRIO_IMG.art(65), desc: '普通 · 芙蘭 雪花芙蘭' },
  { name: '芙蘭·蓬鬆芙蘭', rarity: 'common', img: SANRIO_IMG.art(66), desc: '普通 · 芙蘭 蓬鬆芙蘭' },
  { name: '卡布奇諾·耳罩冬日', rarity: 'common', img: SANRIO_IMG.art(67), desc: '普通 · 卡布奇諾 耳罩冬日' },
  { name: '卡布奇諾·卡布午睡', rarity: 'common', img: SANRIO_IMG.art(68), desc: '普通 · 卡布奇諾 卡布午睡' },
  { name: '濃縮咖啡·頂帽紳士', rarity: 'common', img: SANRIO_IMG.art(69), desc: '普通 · 濃縮咖啡 頂帽紳士' },
  { name: '濃縮咖啡·濃縮地圖', rarity: 'common', img: SANRIO_IMG.art(70), desc: '普通 · 濃縮咖啡 濃縮地圖' },
  { name: '帕蒂·紅裙帕蒂', rarity: 'common', img: SANRIO_IMG.art(71), desc: '普通 · 帕蒂 紅裙帕蒂' },
  { name: '帕蒂·蛋糕甜品', rarity: 'common', img: SANRIO_IMG.art(72), desc: '普通 · 帕蒂 蛋糕甜品' },
  { name: '吉米·寬帽吉米', rarity: 'common', img: SANRIO_IMG.art(73), desc: '普通 · 吉米 寬帽吉米' },
  { name: '吉米·足球明星', rarity: 'common', img: SANRIO_IMG.art(74), desc: '普通 · 吉米 足球明星' },
  { name: '烏薩哈娜·櫻花兔耳', rarity: 'common', img: SANRIO_IMG.art(75), desc: '普通 · 烏薩哈娜 櫻花兔耳' },
  { name: '烏薩哈娜·兔子舞會', rarity: 'common', img: SANRIO_IMG.art(76), desc: '普通 · 烏薩哈娜 兔子舞會' },
  { name: '可吉·小麥精靈', rarity: 'common', img: SANRIO_IMG.art(77), desc: '普通 · 可吉 小麥精靈' },
  { name: '可吉·雲朵精靈', rarity: 'common', img: SANRIO_IMG.art(78), desc: '普通 · 可吉 雲朵精靈' },
  { name: '小香香·香水蝴蝶', rarity: 'common', img: SANRIO_IMG.art(79), desc: '普通 · 小香香 香水蝴蝶' },
  { name: '小香香·百合花束', rarity: 'common', img: SANRIO_IMG.art(80), desc: '普通 · 小香香 百合花束' },
  { name: '帕塔派·蝴蝶飛舞', rarity: 'common', img: SANRIO_IMG.art(81), desc: '普通 · 帕塔派 蝴蝶飛舞' },
  { name: '帕塔派·派對拍手', rarity: 'common', img: SANRIO_IMG.art(82), desc: '普通 · 帕塔派 派對拍手' },
  { name: '座敷狸·座敷榻榻米', rarity: 'common', img: SANRIO_IMG.art(83), desc: '普通 · 座敷狸 座敷榻榻米' },
  { name: '座敷狸·鐮倉小町', rarity: 'common', img: SANRIO_IMG.art(84), desc: '普通 · 座敷狸 鐮倉小町' },
  { name: '花丸鬼·花丸跳舞', rarity: 'common', img: SANRIO_IMG.art(85), desc: '普通 · 花丸鬼 花丸跳舞' },
  { name: '花丸鬼·鬼火跳躍', rarity: 'common', img: SANRIO_IMG.art(86), desc: '普通 · 花丸鬼 鬼火跳躍' },
  { name: '熊寶·熊貓抱抱', rarity: 'common', img: SANRIO_IMG.art(87), desc: '普通 · 熊寶 熊貓抱抱' },
  { name: '熊寶·竹葉熊貓', rarity: 'common', img: SANRIO_IMG.art(88), desc: '普通 · 熊寶 竹葉熊貓' },
  { name: '蘭德里·毛巾折疊', rarity: 'common', img: SANRIO_IMG.art(89), desc: '普通 · 蘭德里 毛巾折疊' },
  { name: '蘭德里·陽光晾曬', rarity: 'common', img: SANRIO_IMG.art(90), desc: '普通 · 蘭德里 陽光晾曬' },
  { name: '森小子·森林探險', rarity: 'common', img: SANRIO_IMG.art(91), desc: '普通 · 森小子 森林探險' },
  { name: '森小子·螢火森林', rarity: 'common', img: SANRIO_IMG.art(92), desc: '普通 · 森小子 螢火森林' },
  { name: '抹茶兔·抹茶甜點', rarity: 'common', img: SANRIO_IMG.art(93), desc: '普通 · 抹茶兔 抹茶甜點' },
  { name: '抹茶兔·和果子', rarity: 'common', img: SANRIO_IMG.art(94), desc: '普通 · 抹茶兔 和果子' },
  { name: '櫻花兔·櫻花飛舞', rarity: 'common', img: SANRIO_IMG.art(95), desc: '普通 · 櫻花兔 櫻花飛舞' },
  { name: '櫻花兔·祭典燈籠', rarity: 'common', img: SANRIO_IMG.art(96), desc: '普通 · 櫻花兔 祭典燈籠' },
  { name: '糖果妹·糖果甜心', rarity: 'common', img: SANRIO_IMG.art(97), desc: '普通 · 糖果妹 糖果甜心' },
  { name: '糖果妹·棉花糖雲', rarity: 'common', img: SANRIO_IMG.art(98), desc: '普通 · 糖果妹 棉花糖雲' },
  { name: '可憐咪·辦公室淡定', rarity: 'common', img: SANRIO_IMG.art(99), desc: '普通 · 可憐咪 辦公室淡定' },
  { name: '可憐咪·煙花慶典', rarity: 'common', img: SANRIO_IMG.art(100), desc: '普通 · 可憐咪 煙花慶典' }
];
