/* Sanrio 卡池：100 張獨立卡片 */
const SANRIO_ART_VER = 2;
const SANRIO_IMG = {
  party: `assets/img/cinnamoroll/cinnamoroll-party.png?v=${SANRIO_ART_VER}`,
  prince: `assets/img/cinnamoroll/cinnamoroll-prince.png?v=${SANRIO_ART_VER}`,
  winter: `assets/img/cinnamoroll/cinnamoroll-winter.png?v=${SANRIO_ART_VER}`,
  solo: `assets/img/cinnamoroll/cinnamoroll-solo.png?v=${SANRIO_ART_VER}`,
  mocha: `assets/img/cinnamoroll/cinna-mocha.png?v=${SANRIO_ART_VER}`,
  milk: `assets/img/cinnamoroll/cinna-milk.png?v=${SANRIO_ART_VER}`,
  chiffon: `assets/img/cinnamoroll/cinna-chiffon.png?v=${SANRIO_ART_VER}`,
  cappuccino: `assets/img/cinnamoroll/cinna-cappuccino.png?v=${SANRIO_ART_VER}`,
  espresso: `assets/img/cinnamoroll/cinna-espresso.png?v=${SANRIO_ART_VER}`,
  ref: (n) => `assets/img/cinnamoroll/cards/art-${String(n).padStart(3, '0')}.svg?v=${SANRIO_ART_VER}`,
  art: (n) => `assets/img/cinnamoroll/cards/art-${String(n).padStart(3, '0')}.svg?v=${SANRIO_ART_VER}`
};

const SANRIO_DECK = [
  { name: 'Sanrio 朋友·永遠版', rarity: 'ssr', img: SANRIO_IMG.party, desc: '生日派對全員到齊，蛋糕、氣球同禮物滿載！' },
  { name: '美樂蒂·皇家音樂會', rarity: 'ssr', img: SANRIO_IMG.prince, desc: '皇冠、禮服同豎琴，皇家音樂巡遊最華麗一刻。' },
  { name: '庫洛米·星空星座', rarity: 'ssr', img: SANRIO_IMG.art(5), desc: '深夜星空、星座天馬，同你一齊遨遊宇宙。' },
  { name: 'Sanrio 朋友·壽司聯名', rarity: 'ur', img: SANRIO_IMG.art(16), desc: 'Sushiro 聯名冬日夜景，壽司星座閃閃發光。' },
  { name: '布丁狗和朋友·極光團聚', rarity: 'ur', img: SANRIO_IMG.art(17), desc: '雪地圍巾、星光滿天，朋友仔暖暖團聚。' },
  { name: '大眼蛙和朋友·冬日版', rarity: 'ur', img: SANRIO_IMG.winter, desc: '雪花紛飛冬日慶典，肉桂狗同伙伴齊聚。' },
  { name: '蛋黃哥·夏日派對', rarity: 'ur', img: SANRIO_IMG.art(14), desc: '沙灘汽水、太陽眼鏡，夏日狂歡派對！' },
  { name: '酷企鵝·慶典煙花', rarity: 'ur', img: SANRIO_IMG.art(15), desc: '彩帶煙花、甜蜜慶祝，華麗節日氣氛。' },
  { name: '帕恰狗·夏日徽章', rarity: 'ur', img: SANRIO_IMG.art(3), desc: 'Sanrio 夏日徽章系列，六角色齊晒。' },
  { name: '雙子星·雲海飛行', rarity: 'ur', img: SANRIO_IMG.art(6), desc: '乘著長耳朵飛過雲海，藍天白雲好夢幻。' },
  { name: '大耳狗·茶會盛宴', rarity: 'ur', img: SANRIO_IMG.art(7), desc: '茶杯禮帽、精緻茶點，夢幻下午茶。' },
  { name: '許願兔·星願籃子', rarity: 'ur', img: SANRIO_IMG.art(9), desc: 'Sanrio 朋友仔齊坐花籃，繽紛夏日風。' },
  { name: '毛絨熊·銀河漫步', rarity: 'ur', img: SANRIO_IMG.art(24), desc: '銀河星球、閃亮星塵，漫步奇幻夜空。' },
  { name: '肉桂狗·濃縮·紳士版', rarity: 'sr', img: SANRIO_IMG.espresso, desc: '優雅紳士造型，濃縮咖啡好帥氣！' },
  { name: '肉桂狗·牛奶·彩虹毯版', rarity: 'sr', img: SANRIO_IMG.milk, desc: '奶嘴同彩虹小毯，奶味十足超可愛。' },
  { name: '肉桂狗·芙蘭·雪花版', rarity: 'sr', img: SANRIO_IMG.chiffon, desc: '毛茸茸芙蘭，雪花圍巾暖呼呼。' },
  { name: '肉桂狗·摩卡·櫻花版', rarity: 'sr', img: SANRIO_IMG.mocha, desc: '蝴蝶結摩卡，櫻花飄落好浪漫。' },
  { name: '肉桂狗·卡布·耳罩版', rarity: 'sr', img: SANRIO_IMG.cappuccino, desc: '暖暖耳罩卡布奇諾，冬日慵懒風。' },
  { name: '肉桂狗·雲朵飄飄', rarity: 'sr', img: SANRIO_IMG.art(2), desc: '多隻肉桂狗浮在雲端，夢幻天空圖案。' },
  { name: '布丁狗·泰迪熊驚喜', rarity: 'sr', img: SANRIO_IMG.art(10), desc: '抱著小熊從畫面探頭，驚喜滿滿。' },
  { name: '大眼蛙·雪糕甜蜜', rarity: 'sr', img: SANRIO_IMG.art(11), desc: '手拿雪糕、雪花飄飄，甜蜜冬日滋味。' },
  { name: '蛋黃哥·星座許願', rarity: 'sr', img: SANRIO_IMG.art(23), desc: '仰望星空許願，星座閃爍好神奇。' },
  { name: '酷企鵝·經典版', rarity: 'sr', img: SANRIO_IMG.solo, desc: '經典肉桂狗造型，長耳朵藍眼睛。' },
  { name: '帕恰狗·雲朵午睡', rarity: 'sr', img: SANRIO_IMG.art(8), desc: '躺在雲朵上午睡，舒服到打哈欠。' },
  { name: '雙子星·花園野餐', rarity: 'sr', img: SANRIO_IMG.art(12), desc: '花園野餐墊上，享受陽光同點心。' },
  { name: '大耳狗·泰迪探頭', rarity: 'rare', img: SANRIO_IMG.art(1), desc: '抱著小熊好奇探頭，萌度爆表。' },
  { name: '許願兔·雪糕座', rarity: 'rare', img: SANRIO_IMG.art(4), desc: '坐在雪地裡吃雪糕，開心笑呵呵。' },
  { name: '毛絨熊·花園散步', rarity: 'rare', img: SANRIO_IMG.art(13), desc: '花園小徑散步，微風吹過長耳朵。' },
  { name: '漢頓·萌萌臉', rarity: 'rare', img: SANRIO_IMG.art(18), desc: '特寫萌萌臉蛋，藍眼睛粉腮紅。' },
  { name: '可可豆·眨眼版', rarity: 'rare', img: SANRIO_IMG.art(19), desc: '俏皮眨眼，逗你開心。' },
  { name: 'Hello Kitty·微笑版', rarity: 'rare', img: SANRIO_IMG.art(20), desc: '甜甜微笑，治癒系小天使。' },
  { name: '美樂蒂·簡約版', rarity: 'rare', img: SANRIO_IMG.art(21), desc: '簡約線條風，清新可愛。' },
  { name: '庫洛米·迷你版', rarity: 'rare', img: SANRIO_IMG.art(22), desc: '迷你Q版造型，放進口袋剛好。' },
  { name: '肉桂狗·摩卡·蝴蝶結版', rarity: 'rare', img: SANRIO_IMG.art(58), desc: '粉蝴蝶結摩卡，甜美登場。' },
  { name: '肉桂狗·牛奶·奶嘴版', rarity: 'rare', img: SANRIO_IMG.art(59), desc: '含著奶嘴的牛奶，軟綿綿。' },
  { name: '肉桂狗·芙蘭·毛帽版', rarity: 'rare', img: SANRIO_IMG.art(60), desc: '戴毛帽的芙蘭，暖笠笠。' },
  { name: '肉桂狗·卡布·枕頭版', rarity: 'rare', img: SANRIO_IMG.art(61), desc: '抱枕頭打瞌睡的卡布奇諾。' },
  { name: '肉桂狗·濃縮·背包版', rarity: 'rare', img: SANRIO_IMG.art(62), desc: '背著小背包準備探險。' },
  { name: '帕恰狗·雲朵版', rarity: 'rare', img: SANRIO_IMG.art(63), desc: '坐在軟綿綿雲朵上發呆。' },
  { name: '雙子星·星星版', rarity: 'rare', img: SANRIO_IMG.art(64), desc: '手捧閃亮小星星。' },
  { name: '大耳狗·圍巾版', rarity: 'rare', img: SANRIO_IMG.art(65), desc: '粉白條紋圍巾，冬日必備。' },
  { name: '許願兔·草莓版', rarity: 'rare', img: SANRIO_IMG.art(66), desc: '頭頂草莓，甜甜水果風。' },
  { name: '毛絨熊·牛奶糖版', rarity: 'rare', img: SANRIO_IMG.art(67), desc: '牛奶糖色調，軟糯可愛。' },
  { name: '漢頓·棉花糖版', rarity: 'rare', img: SANRIO_IMG.art(68), desc: '像棉花糖一樣輕盈蓬鬆。' },
  { name: '可可豆·晴天版', rarity: 'rare', img: SANRIO_IMG.art(69), desc: '晴天太陽下蹦蹦跳跳。' },
  { name: 'Hello Kitty·雨天版', rarity: 'rare', img: SANRIO_IMG.art(70), desc: '撐小雨傘，雨滴叮叮噹。' },
  { name: '美樂蒂·咖啡廳版', rarity: 'rare', img: SANRIO_IMG.art(71), desc: '咖啡廳角落靜靜享受下午茶。' },
  { name: '庫洛米·睡覺版', rarity: 'rare', img: SANRIO_IMG.art(72), desc: '抱著枕頭呼呼大睡。' },
  { name: '肉桂狗·飛行版', rarity: 'rare', img: SANRIO_IMG.art(73), desc: '耳朵當翅膀，咻一聲飛走。' },
  { name: '布丁狗·生日版', rarity: 'rare', img: SANRIO_IMG.art(74), desc: '戴生日帽吹蠟燭，好開心。' },
  { name: '大眼蛙·雲朵', rarity: 'common', img: SANRIO_IMG.art(33), desc: '普通雲朵系列卡片。' },
  { name: '蛋黃哥·星星', rarity: 'common', img: SANRIO_IMG.art(34), desc: '普通星星系列卡片。' },
  { name: '肉桂狗·摩卡·下午茶', rarity: 'common', img: SANRIO_IMG.art(35), desc: '摩卡下午茶時光。' },
  { name: '肉桂狗·牛奶·搖籃', rarity: 'common', img: SANRIO_IMG.art(36), desc: '牛奶在搖籃裡打盹。' },
  { name: '肉桂狗·芙蘭·滑雪', rarity: 'common', img: SANRIO_IMG.art(37), desc: '芙蘭第一次滑雪。' },
  { name: '肉桂狗·卡布·午覺', rarity: 'common', img: SANRIO_IMG.art(38), desc: '卡布奇諾午覺時間。' },
  { name: '肉桂狗·濃縮·地圖', rarity: 'common', img: SANRIO_IMG.art(39), desc: '濃縮咖啡研究地圖。' },
  { name: '毛絨熊·櫻花', rarity: 'common', img: SANRIO_IMG.art(40), desc: '櫻花樹下野餐。' },
  { name: '漢頓·蝴蝶結', rarity: 'common', img: SANRIO_IMG.art(41), desc: '頸上蝴蝶結好靚。' },
  { name: '可可豆·草莓', rarity: 'common', img: SANRIO_IMG.art(42), desc: '草莓甜點時間。' },
  { name: 'Hello Kitty·牛奶糖', rarity: 'common', img: SANRIO_IMG.art(43), desc: '牛奶糖香味撲鼻。' },
  { name: '美樂蒂·棉花糖', rarity: 'common', img: SANRIO_IMG.art(44), desc: '棉花糖雲朵般柔軟。' },
  { name: '庫洛米·晴天', rarity: 'common', img: SANRIO_IMG.art(45), desc: '晴天出門散步。' },
  { name: '肉桂狗·雨天', rarity: 'common', img: SANRIO_IMG.art(46), desc: '雨天在家看窗外。' },
  { name: '布丁狗·聖誕', rarity: 'common', img: SANRIO_IMG.art(47), desc: '聖誕帽同小禮物。' },
  { name: '大眼蛙·新年', rarity: 'common', img: SANRIO_IMG.art(48), desc: '新年利是好運到。' },
  { name: '肉桂狗·摩卡·購物', rarity: 'common', img: SANRIO_IMG.art(49), desc: '摩卡逛街買甜品。' },
  { name: '肉桂狗·牛奶·玩具熊', rarity: 'common', img: SANRIO_IMG.art(50), desc: '牛奶抱玩具熊入睡。' },
  { name: '肉桂狗·芙蘭·雪人', rarity: 'common', img: SANRIO_IMG.art(51), desc: '芙蘭堆了一個小雪人。' },
  { name: '肉桂狗·卡布·毛毯', rarity: 'common', img: SANRIO_IMG.art(52), desc: '卡布奇諾裹毛毯睇書。' },
  { name: '肉桂狗·濃縮·禮帽', rarity: 'common', img: SANRIO_IMG.art(53), desc: '濃縮咖啡戴禮帽。' },
  { name: '許願兔·音符', rarity: 'common', img: SANRIO_IMG.art(54), desc: '哼着小曲好開心。' },
  { name: '毛絨熊·氣球', rarity: 'common', img: SANRIO_IMG.art(55), desc: '手拿彩色氣球。' },
  { name: '漢頓·禮物', rarity: 'common', img: SANRIO_IMG.art(56), desc: '神秘禮物盒一份。' },
  { name: '可可豆·雪花', rarity: 'common', img: SANRIO_IMG.art(57), desc: '接住一片小雪花。' },
  { name: 'Hello Kitty·彩虹', rarity: 'common', img: SANRIO_IMG.art(75), desc: '雨後彩虹好靚。' },
  { name: '美樂蒂·月亮', rarity: 'common', img: SANRIO_IMG.art(76), desc: '月光下輕輕飛翔。' },
  { name: '肉桂狗·摩卡·拍照', rarity: 'common', img: SANRIO_IMG.art(77), desc: '摩卡舉相機自拍。' },
  { name: '肉桂狗·牛奶·泡泡', rarity: 'common', img: SANRIO_IMG.art(78), desc: '牛奶吹彩色泡泡。' },
  { name: '肉桂狗·芙蘭·熱可可', rarity: 'common', img: SANRIO_IMG.art(79), desc: '芙蘭捧熱可可暖手。' },
  { name: '肉桂狗·卡布·慵懶', rarity: 'common', img: SANRIO_IMG.art(80), desc: '慵懶伸懶腰。' },
  { name: '肉桂狗·濃縮·筆記', rarity: 'common', img: SANRIO_IMG.art(81), desc: '濃縮咖啡寫筆記。' },
  { name: '酷企鵝·花朵', rarity: 'common', img: SANRIO_IMG.art(82), desc: '頭戴小花冠。' },
  { name: '帕恰狗·愛心', rarity: 'common', img: SANRIO_IMG.art(83), desc: '比心心送俾你。' },
  { name: '雙子星·糖果', rarity: 'common', img: SANRIO_IMG.art(84), desc: '糖果罐裝滿甜蜜。' },
  { name: '大耳狗·餅乾', rarity: 'common', img: SANRIO_IMG.art(85), desc: '剛出爐小餅乾。' },
  { name: '許願兔·蛋糕', rarity: 'common', img: SANRIO_IMG.art(86), desc: '小蛋糕好诱人。' },
  { name: '毛絨熊·冰淇淋', rarity: 'common', img: SANRIO_IMG.art(87), desc: '三球冰淇淋！' },
  { name: '漢頓·太陽', rarity: 'common', img: SANRIO_IMG.art(88), desc: '向太陽說早安。' },
  { name: '可可豆·咖啡', rarity: 'common', img: SANRIO_IMG.art(89), desc: '早晨一杯咖啡。' },
  { name: '肉桂狗·摩卡·甜品', rarity: 'common', img: SANRIO_IMG.art(90), desc: '摩卡甜品時光。' },
  { name: '肉桂狗·牛奶·糖果', rarity: 'common', img: SANRIO_IMG.art(91), desc: '牛奶含糖果笑咪咪。' },
  { name: '肉桂狗·芙蘭·手套', rarity: 'common', img: SANRIO_IMG.art(92), desc: '芙蘭戴暖暖手套。' },
  { name: '肉桂狗·卡布·柔軟', rarity: 'common', img: SANRIO_IMG.art(93), desc: '柔軟蓬鬆好舒服。' },
  { name: '肉桂狗·濃縮·望遠鏡', rarity: 'common', img: SANRIO_IMG.art(94), desc: '用望遠鏡看星星。' },
  { name: '大眼蛙·風箏', rarity: 'common', img: SANRIO_IMG.art(95), desc: '放風箏好得意。' },
  { name: '蛋黃哥·貝殼', rarity: 'common', img: SANRIO_IMG.art(96), desc: '海邊拾貝殼。' },
  { name: '酷企鵝·楓葉', rarity: 'common', img: SANRIO_IMG.art(97), desc: '秋天楓葉飄落。' },
  { name: '帕恰狗·鈴鐺', rarity: 'common', img: SANRIO_IMG.art(98), desc: '頸上小鈴鐺叮噹響。' },
  { name: '雙子星·限定', rarity: 'common', img: SANRIO_IMG.art(99), desc: '限定普通版收藏卡。' }
];
