/* SANRIO_DECK 卡池：100 張獨立卡片，每角色最多 2 張 */
const SANRIO_ART_VER = 4;
const SANRIO_IMG = {
  art: (n) => `assets/img/cinnamoroll/cards/art-${String(n).padStart(3, '0')}.svg?v=${SANRIO_ART_VER}`
};

const SANRIO_DECK = [
  { name: 'Hello Kitty·草莓派對', rarity: 'ssr', img: SANRIO_IMG.art(1), desc: '傳說 · Hello Kitty 草莓派對' },
  { name: 'Hello Kitty·蝴蝶結經典', rarity: 'ssr', img: SANRIO_IMG.art(2), desc: '傳說 · Hello Kitty 蝴蝶結經典' },
  { name: '美樂蒂·櫻花春日', rarity: 'ssr', img: SANRIO_IMG.art(3), desc: '傳說 · 美樂蒂 櫻花春日' },
  { name: '美樂蒂·野餐籃子', rarity: 'ur', img: SANRIO_IMG.art(4), desc: '極稀有 · 美樂蒂 野餐籃子' },
  { name: '庫洛米·惡魔蝴蝶結', rarity: 'ur', img: SANRIO_IMG.art(5), desc: '極稀有 · 庫洛米 惡魔蝴蝶結' },
  { name: '庫洛米·骷髏頭巾', rarity: 'ur', img: SANRIO_IMG.art(6), desc: '極稀有 · 庫洛米 骷髏頭巾' },
  { name: '肉桂狗·雲朵飛行', rarity: 'ur', img: SANRIO_IMG.art(7), desc: '極稀有 · 肉桂狗 雲朵飛行' },
  { name: '肉桂狗·午睡枕頭', rarity: 'ur', img: SANRIO_IMG.art(8), desc: '極稀有 · 肉桂狗 午睡枕頭' },
  { name: '布丁狗·帽子貝雷', rarity: 'ur', img: SANRIO_IMG.art(9), desc: '極稀有 · 布丁狗 帽子貝雷' },
  { name: '布丁狗·布丁游泳', rarity: 'ur', img: SANRIO_IMG.art(10), desc: '極稀有 · 布丁狗 布丁游泳' },
  { name: '大眼蛙·荷葉泳圈', rarity: 'ur', img: SANRIO_IMG.art(11), desc: '極稀有 · 大眼蛙 荷葉泳圈' },
  { name: '大眼蛙·雨傘跳跳', rarity: 'ur', img: SANRIO_IMG.art(12), desc: '極稀有 · 大眼蛙 雨傘跳跳' },
  { name: '蛋黃哥·懶懶煎蛋', rarity: 'ur', img: SANRIO_IMG.art(13), desc: '極稀有 · 蛋黃哥 懶懶煎蛋' },
  { name: '蛋黃哥·醬油碟子', rarity: 'sr', img: SANRIO_IMG.art(14), desc: '超稀有 · 蛋黃哥 醬油碟子' },
  { name: '酷企鵝·搖滾墨鏡', rarity: 'sr', img: SANRIO_IMG.art(15), desc: '超稀有 · 酷企鵝 搖滾墨鏡' },
  { name: '酷企鵝·滑板極限', rarity: 'sr', img: SANRIO_IMG.art(16), desc: '超稀有 · 酷企鵝 滑板極限' },
  { name: '帕恰狗·藍耳飛奔', rarity: 'sr', img: SANRIO_IMG.art(17), desc: '超稀有 · 帕恰狗 藍耳飛奔' },
  { name: '帕恰狗·足球射門', rarity: 'sr', img: SANRIO_IMG.art(18), desc: '超稀有 · 帕恰狗 足球射門' },
  { name: '奇奇·星星閃亮', rarity: 'sr', img: SANRIO_IMG.art(19), desc: '超稀有 · 奇奇 星星閃亮' },
  { name: '奇奇·彩虹橋', rarity: 'sr', img: SANRIO_IMG.art(20), desc: '超稀有 · 奇奇 彩虹橋' },
  { name: '拉拉·月亮甜夢', rarity: 'sr', img: SANRIO_IMG.art(21), desc: '超稀有 · 拉拉 月亮甜夢' },
  { name: '拉拉·太陽暖暖', rarity: 'sr', img: SANRIO_IMG.art(22), desc: '超稀有 · 拉拉 太陽暖暖' },
  { name: '燕尾服山姆·領結紳士', rarity: 'sr', img: SANRIO_IMG.art(23), desc: '超稀有 · 燕尾服山姆 領結紳士' },
  { name: '燕尾服山姆·魚子壽司', rarity: 'sr', img: SANRIO_IMG.art(24), desc: '超稀有 · 燕尾服山姆 魚子壽司' },
  { name: '漢頓·噴水表演', rarity: 'sr', img: SANRIO_IMG.art(25), desc: '超稀有 · 漢頓 噴水表演' },
  { name: '漢頓·海洋探險', rarity: 'rare', img: SANRIO_IMG.art(26), desc: '稀有 · 漢頓 海洋探險' },
  { name: '巧克貓·巧克力豆', rarity: 'rare', img: SANRIO_IMG.art(27), desc: '稀有 · 巧克貓 巧克力豆' },
  { name: '巧克貓·黑貓夜行', rarity: 'rare', img: SANRIO_IMG.art(28), desc: '稀有 · 巧克貓 黑貓夜行' },
  { name: '毛毯熊·毛毯暖暖', rarity: 'rare', img: SANRIO_IMG.art(29), desc: '稀有 · 毛毯熊 毛毯暖暖' },
  { name: '毛毯熊·枕頭大戰', rarity: 'rare', img: SANRIO_IMG.art(30), desc: '稀有 · 毛毯熊 枕頭大戰' },
  { name: '邦邦兔·緞帶蝴蝶', rarity: 'rare', img: SANRIO_IMG.art(31), desc: '稀有 · 邦邦兔 緞帶蝴蝶' },
  { name: '邦邦兔·禮物緞帶', rarity: 'rare', img: SANRIO_IMG.art(32), desc: '稀有 · 邦邦兔 禮物緞帶' },
  { name: '許願兔·許願流星', rarity: 'rare', img: SANRIO_IMG.art(33), desc: '稀有 · 許願兔 許願流星' },
  { name: '許願兔·兔子洞', rarity: 'rare', img: SANRIO_IMG.art(34), desc: '稀有 · 許願兔 兔子洞' },
  { name: '可可豆·可可香氣', rarity: 'rare', img: SANRIO_IMG.art(35), desc: '稀有 · 可可豆 可可香氣' },
  { name: '可可豆·熱可可', rarity: 'rare', img: SANRIO_IMG.art(36), desc: '稀有 · 可可豆 熱可可' },
  { name: '必愛諾·愛心抱抱', rarity: 'rare', img: SANRIO_IMG.art(37), desc: '稀有 · 必愛諾 愛心抱抱' },
  { name: '必愛諾·諾亞方舟', rarity: 'rare', img: SANRIO_IMG.art(38), desc: '稀有 · 必愛諾 諾亞方舟' },
  { name: '淘氣猴·香蕉搗蛋', rarity: 'rare', img: SANRIO_IMG.art(39), desc: '稀有 · 淘氣猴 香蕉搗蛋' },
  { name: '淘氣猴·叢林藤蔓', rarity: 'rare', img: SANRIO_IMG.art(40), desc: '稀有 · 淘氣猴 叢林藤蔓' },
  { name: '蜜糖邦妮·蜜糖罐', rarity: 'rare', img: SANRIO_IMG.art(41), desc: '稀有 · 蜜糖邦妮 蜜糖罐' },
  { name: '蜜糖邦妮·邦妮花園', rarity: 'rare', img: SANRIO_IMG.art(42), desc: '稀有 · 蜜糖邦妮 邦妮花園' },
  { name: '跳跳蛙·荷葉跳水', rarity: 'rare', img: SANRIO_IMG.art(43), desc: '稀有 · 跳跳蛙 荷葉跳水' },
  { name: '跳跳蛙·池塘荷葉', rarity: 'rare', img: SANRIO_IMG.art(44), desc: '稀有 · 跳跳蛙 池塘荷葉' },
  { name: '小香香·花香蝴蝶', rarity: 'rare', img: SANRIO_IMG.art(45), desc: '稀有 · 小香香 花香蝴蝶' },
  { name: '小香香·香水百合', rarity: 'rare', img: SANRIO_IMG.art(46), desc: '稀有 · 小香香 香水百合' },
  { name: '豆豆鴨·鴨鴨游泳', rarity: 'rare', img: SANRIO_IMG.art(47), desc: '稀有 · 豆豆鴨 鴨鴨游泳' },
  { name: '豆豆鴨·黃鴨游泳圈', rarity: 'rare', img: SANRIO_IMG.art(48), desc: '稀有 · 豆豆鴨 黃鴨游泳圈' },
  { name: '鋼牙妹·鋼牙閃亮', rarity: 'rare', img: SANRIO_IMG.art(49), desc: '稀有 · 鋼牙妹 鋼牙閃亮' },
  { name: '鋼牙妹·牙套閃耀', rarity: 'rare', img: SANRIO_IMG.art(50), desc: '稀有 · 鋼牙妹 牙套閃耀' },
  { name: '野狼健·野營帳篷', rarity: 'common', img: SANRIO_IMG.art(51), desc: '普通 · 野狼健 野營帳篷' },
  { name: '野狼健·月亮嚎叫', rarity: 'common', img: SANRIO_IMG.art(52), desc: '普通 · 野狼健 月亮嚎叫' },
  { name: '小浣熊·洗臉盆', rarity: 'common', img: SANRIO_IMG.art(53), desc: '普通 · 小浣熊 洗臉盆' },
  { name: '小浣熊·森林浣洗', rarity: 'common', img: SANRIO_IMG.art(54), desc: '普通 · 小浣熊 森林浣洗' },
  { name: '海獅君·海獅頂球', rarity: 'common', img: SANRIO_IMG.art(55), desc: '普通 · 海獅君 海獅頂球' },
  { name: '海獅君·球技表演', rarity: 'common', img: SANRIO_IMG.art(56), desc: '普通 · 海獅君 球技表演' },
  { name: '鴨仔雷蒙·雷蒙帽', rarity: 'common', img: SANRIO_IMG.art(57), desc: '普通 · 鴨仔雷蒙 雷蒙帽' },
  { name: '鴨仔雷蒙·鴨帽造型', rarity: 'common', img: SANRIO_IMG.art(58), desc: '普通 · 鴨仔雷蒙 鴨帽造型' },
  { name: '摩卡·咖啡午茶', rarity: 'common', img: SANRIO_IMG.art(59), desc: '普通 · 摩卡 咖啡午茶' },
  { name: '摩卡·櫻花摩卡', rarity: 'common', img: SANRIO_IMG.art(60), desc: '普通 · 摩卡 櫻花摩卡' },
  { name: '牛奶·奶嘴搖籃', rarity: 'common', img: SANRIO_IMG.art(61), desc: '普通 · 牛奶 奶嘴搖籃' },
  { name: '牛奶·彩虹毯子', rarity: 'common', img: SANRIO_IMG.art(62), desc: '普通 · 牛奶 彩虹毯子' },
  { name: '芙蘭·雪花圍巾', rarity: 'common', img: SANRIO_IMG.art(63), desc: '普通 · 芙蘭 雪花圍巾' },
  { name: '芙蘭·蓬鬆芙蘭', rarity: 'common', img: SANRIO_IMG.art(64), desc: '普通 · 芙蘭 蓬鬆芙蘭' },
  { name: '卡布奇諾·耳罩冬日', rarity: 'common', img: SANRIO_IMG.art(65), desc: '普通 · 卡布奇諾 耳罩冬日' },
  { name: '卡布奇諾·卡布午睡', rarity: 'common', img: SANRIO_IMG.art(66), desc: '普通 · 卡布奇諾 卡布午睡' },
  { name: '濃縮咖啡·紳士禮帽', rarity: 'common', img: SANRIO_IMG.art(67), desc: '普通 · 濃縮咖啡 紳士禮帽' },
  { name: '濃縮咖啡·濃縮地圖', rarity: 'common', img: SANRIO_IMG.art(68), desc: '普通 · 濃縮咖啡 濃縮地圖' },
  { name: '大耳狗·長耳飄飄', rarity: 'common', img: SANRIO_IMG.art(69), desc: '普通 · 大耳狗 長耳飄飄' },
  { name: '大耳狗·雲朵大耳', rarity: 'common', img: SANRIO_IMG.art(70), desc: '普通 · 大耳狗 雲朵大耳' },
  { name: '小倉鼠·瓜子倉庫', rarity: 'common', img: SANRIO_IMG.art(71), desc: '普通 · 小倉鼠 瓜子倉庫' },
  { name: '小倉鼠·倉鼠跑輪', rarity: 'common', img: SANRIO_IMG.art(72), desc: '普通 · 小倉鼠 倉鼠跑輪' },
  { name: '小綿羊·羊毛暖暖', rarity: 'common', img: SANRIO_IMG.art(73), desc: '普通 · 小綿羊 羊毛暖暖' },
  { name: '小綿羊·綿羊數星', rarity: 'common', img: SANRIO_IMG.art(74), desc: '普通 · 小綿羊 綿羊數星' },
  { name: '小刺蝟·刺刺果實', rarity: 'common', img: SANRIO_IMG.art(75), desc: '普通 · 小刺蝟 刺刺果實' },
  { name: '小刺蝟·刺蝟蘋果', rarity: 'common', img: SANRIO_IMG.art(76), desc: '普通 · 小刺蝟 刺蝟蘋果' },
  { name: '小企鵝·企鵝滑冰', rarity: 'common', img: SANRIO_IMG.art(77), desc: '普通 · 小企鵝 企鵝滑冰' },
  { name: '小企鵝·企鵝冰屋', rarity: 'common', img: SANRIO_IMG.art(78), desc: '普通 · 小企鵝 企鵝冰屋' },
  { name: '小狐狸·狐狸尾巴', rarity: 'common', img: SANRIO_IMG.art(79), desc: '普通 · 小狐狸 狐狸尾巴' },
  { name: '小狐狸·狐狸秋天', rarity: 'common', img: SANRIO_IMG.art(80), desc: '普通 · 小狐狸 狐狸秋天' },
  { name: '小鹿斑比·斑比花叢', rarity: 'common', img: SANRIO_IMG.art(81), desc: '普通 · 小鹿斑比 斑比花叢' },
  { name: '小鹿斑比·鹿鳴山谷', rarity: 'common', img: SANRIO_IMG.art(82), desc: '普通 · 小鹿斑比 鹿鳴山谷' },
  { name: '小松鼠·松果收藏', rarity: 'common', img: SANRIO_IMG.art(83), desc: '普通 · 小松鼠 松果收藏' },
  { name: '小松鼠·松鼠堅果', rarity: 'common', img: SANRIO_IMG.art(84), desc: '普通 · 小松鼠 松鼠堅果' },
  { name: '小刺豚·刺豚氣球', rarity: 'common', img: SANRIO_IMG.art(85), desc: '普通 · 小刺豚 刺豚氣球' },
  { name: '小刺豚·河豚海洋', rarity: 'common', img: SANRIO_IMG.art(86), desc: '普通 · 小刺豚 河豚海洋' },
  { name: '小無尾熊·無尾桉樹', rarity: 'common', img: SANRIO_IMG.art(87), desc: '普通 · 小無尾熊 無尾桉樹' },
  { name: '小無尾熊·無尾抱抱', rarity: 'common', img: SANRIO_IMG.art(88), desc: '普通 · 小無尾熊 無尾抱抱' },
  { name: '小樹懶·樹懶吊床', rarity: 'common', img: SANRIO_IMG.art(89), desc: '普通 · 小樹懶 樹懶吊床' },
  { name: '小樹懶·樹懶芒果', rarity: 'common', img: SANRIO_IMG.art(90), desc: '普通 · 小樹懶 樹懶芒果' },
  { name: '小鸚鵡·鸚鵡學舌', rarity: 'common', img: SANRIO_IMG.art(91), desc: '普通 · 小鸚鵡 鸚鵡學舌' },
  { name: '小鸚鵡·鸚鵡彩羽', rarity: 'common', img: SANRIO_IMG.art(92), desc: '普通 · 小鸚鵡 鸚鵡彩羽' },
  { name: '小海豹·海豹頂球', rarity: 'common', img: SANRIO_IMG.art(93), desc: '普通 · 小海豹 海豹頂球' },
  { name: '小海豹·海豹魚兒', rarity: 'common', img: SANRIO_IMG.art(94), desc: '普通 · 小海豹 海豹魚兒' },
  { name: '小水獺·水獺石頭', rarity: 'common', img: SANRIO_IMG.art(95), desc: '普通 · 小水獺 水獺石頭' },
  { name: '小水獺·水獺貝殼', rarity: 'common', img: SANRIO_IMG.art(96), desc: '普通 · 小水獺 水獺貝殼' },
  { name: '小恐龍·恐龍化石', rarity: 'common', img: SANRIO_IMG.art(97), desc: '普通 · 小恐龍 恐龍化石' },
  { name: '小恐龍·恐龍蛋蛋', rarity: 'common', img: SANRIO_IMG.art(98), desc: '普通 · 小恐龍 恐龍蛋蛋' },
  { name: '唐企鵝·企鵝南極', rarity: 'common', img: SANRIO_IMG.art(99), desc: '普通 · 唐企鵝 企鵝南極' },
  { name: '唐企鵝·冰山企鵝', rarity: 'common', img: SANRIO_IMG.art(100), desc: '普通 · 唐企鵝 冰山企鵝' }
];
